In [1]:
import numpy as np
import pandas as pd

pd.options.display.max_rows = 4000
pd.options.display.max_seq_items = 2000
pd.set_option('display.max_columns', None)

# listings

In [2]:
listings = pd.read_csv('listings.csv')
listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,27934,Nice room with superb city view,120437,Nuttee,NaN,Ratchathewi,13.75983,100.54134,Entire home/apt,1905,3,65,2020-01-06,0.50,2,353,0,NaN
1,27979,"Easy going landlord,easy place",120541,Emy,NaN,Bang Na,13.66818,100.61674,Private room,1316,1,0,NaN,NaN,2,358,0,NaN
2,28745,modern-style apartment in Bangkok,123784,Familyroom,NaN,Bang Kapi,13.75232,100.62402,Private room,800,60,0,NaN,NaN,1,365,0,NaN
3,35780,Spacious one bedroom at The Kris Condo Bldg. 3,153730,Sirilak,NaN,Din Daeng,13.78823,100.57256,Private room,1286,7,2,2022-04-01,0.03,1,323,1,NaN
4,941865,Suite Room 3 at MetroPoint,610315,Kasem,NaN,Bang Kapi,13.76872,100.63338,Private room,1905,1,0,NaN,NaN,3,365,0,NaN

In [3]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15854 entries, 0 to 15853
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              15854 non-null  int64
 1   name                            15846 non-null  object
 2   host_id                         15854 non-null  int64
 3   host_name                       15853 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   15854 non-null  object
 6   latitude                        15854 non-null  float64
 7   longitude                       15854 non-null  float64
 8   room_type                       15854 non-null  object
 9   price                           15854 non-null  int64
 10  minimum_nights                  15854 non-null  int64
 11  number_of_reviews               15854 non-null  int64
 12  last_review                     10064 non-null  object
 13  reviews_per_month               10064 non-null  float64
 14  calculated_host_listings_count  15854 non-null  int64
 15  availability_365                15854 non-null  int64
 16  number_of_reviews_ltm           15854 non-null  int64
 17  license                         0 non-null      float64
dtypes: float64(5), int64(8), object(5)
memory usage: 2.2+ MB

# listings2

In [4]:
lastReviewDate = pd.to_datetime(listings.last_review)

display(lastReviewDate.min(), lastReviewDate.max())

Timestamp('2012-12-15 00:00:00')

Timestamp('2022-12-28 00:00:00')

In [5]:
listings2 = pd.read_csv('listings2.csv')
listings2.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,27934,https://www.airbnb.com/rooms/27934,20221228025833,2022-12-28,city scrape,Nice room with superb city view,Our cool and comfortable one bedroom apartment...,It is very center of Bangkok and easy access t...,https://a0.muscache.com/pictures/566374/23157b...,120437,https://www.airbnb.com/users/show/120437,Nuttee,2010-05-08,"Bangkok, Thailand","Hi All, I am nuttee patranavik from Bangkok, T...",within an hour,100%,50%,f,https://a0.muscache.com/im/pictures/user/d05a6...,https://a0.muscache.com/im/pictures/user/d05a6...,Victory Monument,2,2,"['email', 'phone']",t,t,"Samsen Nai, Bangkok, Thailand",Ratchathewi,NaN,13.75983,100.54134,Entire condo,Entire home/apt,3,NaN,1.5 baths,1.0,1.0,"[""Shampoo"", ""Kitchen"", ""Fire extinguisher"", ""F...","$1,905.00",3,90,3.0,3.0,90.0,90.0,3.0,90.0,NaN,t,18,48,78,353,2022-12-28,65,0,0,2012-04-07,2020-01-06,4.85,4.95,4.81,4.97,4.91,4.66,4.75,NaN,f,2,2,0,0,0.50
1,941865,https://www.airbnb.com/rooms/941865,20221228025833,2022-12-28,city scrape,Suite Room 3 at MetroPoint,<b>The space</b><br />MetroPoint Bangkok Hotel...,NaN,https://a0.muscache.com/pictures/13930311/1a1c...,610315,https://www.airbnb.com/users/show/610315,Kasem,2011-05-21,"Bangkok, Thailand",MetroPoint Bangkok Hotel\r\nEasy accessibility...,within an hour,100%,NaN,f,https://a0.muscache.com/im/users/610315/profil...,https://a0.muscache.com/im/users/610315/profil...,Bang Kapi,3,3,"['email', 'phone', 'work_email']",t,t,NaN,Bang Kapi,NaN,13.76872,100.63338,Private room in rental unit,Private room,2,NaN,1 bath,1.0,1.0,"[""Washer"", ""Air conditioning"", ""Breakfast"", ""K...","$1,905.00",1,365,1.0,1.0,365.0,365.0,1.0,365.0,NaN,t,30,60,90,365,2022-12-28,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,3,0,3,0,NaN
2,27979,https://www.airbnb.com/rooms/27979,20221228025833,2022-12-28,city scrape,"Easy going landlord,easy place","<b>The space</b><br />""The village Condominium...",NaN,https://a0.muscache.com/pictures/106247594/1d6...,120541,https://www.airbnb.com/users/show/120541,Emy,2010-05-08,"Bangkok, Thailand",NaN,a few days or more,0%,NaN,f,https://a0.muscache.com/im/users/120541/profil...,https://a0.muscache.com/im/users/120541/profil...,NaN,2,4,"['email', 'phone']",t,f,NaN,Bang Na,NaN,13.66818,100.61674,Private room in rental unit,Private room,2,NaN,1 bath,1.0,2.0,"[""Pool"", ""Washer"", ""First aid kit"", ""Heating"",...","$1,316.00",1,730,1.0,1.0,730.0,730.0,1.0,730.0,NaN,t,23,53,83,358,2022-12-28,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,2,1,1,0,NaN
3,28745,https://www.airbnb.com/rooms/28745,20221228025833,2022-12-28,city scrape,modern-style apartment in Bangkok,A modern-style apartment situated in a cool ne...,Ramkumheang neigbourhood - hip place with food...,https://a0.muscache.com/pictures/160369/92a7ec...,123784,https://www.airbnb.com/users/show/123784,Familyroom,2010-05-12,"Bangkok, Thailand",Welcome to Familyroom Apartment.\r\n\r\nA Chic...,NaN,NaN,NaN,f,https://a0.muscache.com/im/users/123784/profil...,https://a0.muscache.com/im/users/123784/profil...,Bang Kapi,1,1,"['email', 'phone']",t,f,"Bangkok, Thailand",Bang Kapi,NaN,13.75232,100.62402,Private room in rental unit,Private room,2,NaN,1 bath,1.0,1.0,"[""Long term stays allowed""]",$800.00,60,730,60.0,60.0,730.0,730.0,60.0,730.0,NaN,t,30,60,90,365,2022-12-28,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
4,35780,https://www.airbnb.com/rooms/35780,20221228025833,2022-12-28,city scrape,Spacious one bedroom at The Kris Condo Bldg. 3,Cozy and clean apartment at MRT Sutthisarn sta...,"There is McDonald's, Au bon Pain and Max Value...",https://a0.muscache.com/pictures/89302e4b-b529...,153730,https://www.airbnb.com/users/show/153730,Sirilak,2010-06-27,"Bangkok, Thailand",from Bangkok but I'm in and out of the city a ...,within an hour,100%,50%,f,https://a0.muscache.com/im/pictures/user/89c05...,https://a0.muscache.com/im/pictures/user/89c05...,NaN,1,1,"['email', 'phone', 'work_email']",t,t,"Bangkok, Thailand",Din Daeng,NaN,13.78823,100.57256,Private room in rental unit,Private room,2,NaN,1 private bath,1.0,1.0,"[""Clothing storage: closet and dresser"", ""Blen...","$1,286.00",7,366,1.0,7.0,366.0,366.0,7.0,366.0,NaN,t,6,18,48,323,2022-12-28,2,1,0,2016-07-13,2022-04-01,4.50,5.00,4.00,3.50,4.50,4.50,5.00,NaN,f,1,0,1,0,0.03

In [6]:
listings2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15854 entries, 0 to 15853
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            15854 non-null  int64
 1   listing_url                                   15854 non-null  object
 2   scrape_id                                     15854 non-null  int64
 3   last_scraped                                  15854 non-null  object
 4   source                                        15854 non-null  object
 5   name                                          15846 non-null  object
 6   description                                   15248 non-null  object
 7   neighborhood_overview                         8375 non-null   object
 8   picture_url                                   15854 non-null  object
 9   host_id                                       15854 non-null  int64
 10  host_url                                      15854 non-null  object
 11  host_name                                     15853 non-null  object
 12  host_since                                    15854 non-null  object
 13  host_location                                 12259 non-null  object
 14  host_about                                    9399 non-null   object
 15  host_response_time                            12917 non-null  object
 16  host_response_rate                            12917 non-null  object
 17  host_acceptance_rate                          12060 non-null  object
 18  host_is_superhost                             15853 non-null  object
 19  host_thumbnail_url                            15854 non-null  object
 20  host_picture_url                              15854 non-null  object
 21  host_neighbourhood                            8800 non-null   object
 22  host_listings_count                           15854 non-null  int64
 23  host_total_listings_count                     15854 non-null  int64
 24  host_verifications                            15854 non-null  object
 25  host_has_profile_pic                          15854 non-null  object
 26  host_identity_verified                        15854 non-null  object
 27  neighbourhood                                 8375 non-null   object
 28  neighbourhood_cleansed                        15854 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      15854 non-null  float64
 31  longitude                                     15854 non-null  float64
 32  property_type                                 15854 non-null  object
 33  room_type                                     15854 non-null  object
 34  accommodates                                  15854 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                15752 non-null  object
 37  bedrooms                                      14466 non-null  float64
 38  beds                                          15509 non-null  float64
 39  amenities                                     15854 non-null  object
 40  price                                         15854 non-null  object
 41  minimum_nights                                15854 non-null  int64
 42  maximum_nights                                15854 non-null  int64
 43  minimum_minimum_nights                        15853 non-null  float64
 44  maximum_minimum_nights                        15853 non-null  float64
 45  minimum_maximum_nights                        15853 non-null  float64
 46  maximum_maximum_nights                        15853 non-null  float64
 47  minimum_nights_avg_ntm                        15853 non-null  float64
 48  maximum_nights_avg_ntm                        15853 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              15854 non-null  object
 51  availability_30                               15854 non-null  int64
 52  availability_60                               15854 non-null  int64
 53  availability_90                               15854 non-null  int64
 54  availability_365                              15854 non-null  int64
 55  calendar_last_scraped                         15854 non-null  object
 56  number_of_reviews                             15854 non-null  int64
 57  number_of_reviews_ltm                         15854 non-null  int64
 58  number_of_reviews_l30d                        15854 non-null  int64
 59  first_review                                  10064 non-null  object
 60  last_review                                   10064 non-null  object
 61  review_scores_rating                          10064 non-null  float64
 62  review_scores_accuracy                        9924 non-null   float64
 63  review_scores_cleanliness                     9923 non-null   float64
 64  review_scores_checkin                         9919 non-null   float64
 65  review_scores_communication                   9923 non-null   float64
 66  review_scores_location                        9918 non-null   float64
 67  review_scores_value                           9917 non-null   float64
 68  license                                       0 non-null      float64
 69  instant_bookable                              15854 non-null  object
 70  calculated_host_listings_count                15854 non-null  int64
 71  calculated_host_listings_count_entire_homes   15854 non-null  int64
 72  calculated_host_listings_count_private_rooms  15854 non-null  int64
 73  calculated_host_listings_count_shared_rooms   15854 non-null  int64
 74  reviews_per_month                             10064 non-null  float64
dtypes: float64(22), int64(19), object(34)
memory usage: 9.1+ MB

In [7]:
price = listings2.price.str.strip('$').str.replace(',','').astype(float)
price.max()

1100000.0

In [8]:
listings2.property_type.value_counts()

property_type
Entire condo                          3771
Entire rental unit                    3769
Private room in rental unit           1601
Private room in condo                  876
Room in hotel                          695
Room in boutique hotel                 534
Private room in home                   531
Entire home                            420
Private room in hostel                 382
Private room in townhouse              373
Entire serviced apartment              330
Private room in serviced apartment     317
Shared room in hostel                  317
Entire townhouse                       292
Private room in bed and breakfast      268
Room in hostel                         189
Room in aparthotel                     138
Private room                           111
Room in serviced apartment              95
Entire loft                             92
Private room in guesthouse              79
Room in bed and breakfast               73
Private room in guest suite             51
Shared room in rental unit              47
Private room in loft                    36
Entire guest suite                      35
Shared room in townhouse                35
Shared room in bed and breakfast        35
Entire villa                            31
Private room in villa                   30
Entire guesthouse                       28
Private room in tiny home               27
Shared room in home                     25
Shared room in condo                    24
Entire place                            21
Tiny home                               18
Shared room in guesthouse               10
Private room in vacation home            9
Private room in casa particular          9
Private room in resort                   9
Entire home/apt                          8
Private room in nature lodge             8
Shared room in boutique hotel            6
Shared room                              6
Dome                                     5
Farm stay                                5
Private room in barn                     5
Entire bed and breakfast                 5
Private room in houseboat                5
Shared room in guest suite               4
Entire cabin                             4
Entire vacation home                     4
Entire bungalow                          4
Private room in cabin                    4
Private room in bungalow                 3
Private room in kezhan                   3
Entire cottage                           3
Tower                                    3
Shared room in serviced apartment        3
Shared room in hotel                     3
Private room in dome                     2
Room in resort                           2
Shared room in villa                     2
Shared room in dome                      2
Private room in floor                    2
Shared room in casa particular           1
Private room in boat                     1
Private room in tower                    1
Hut                                      1
Shared room in parking space             1
Casa particular                          1
Private room in island                   1
Entire chalet                            1
Barn                                     1
Pension                                  1
Shared room in cave                      1
Earthen home                             1
Private room in earthen home             1
Private room in hut                      1
Floor                                    1
Private room in tipi                     1
Shared room in loft                      1
Private room in farm stay                1
Treehouse                                1
Shipping container                       1
Name: count, dtype: int64

In [9]:
listings2.amenities.unique()

array(['["Shampoo", "Kitchen", "Fire extinguisher", "Free parking on premises", "Long term stays allowed", "Elevator", "Hot water", "Pool", "Dishes and silverware", "Dryer", "Essentials", "Wifi", "Microwave", "Smoke alarm", "Host greets you", "Hair dryer", "Luggage dropoff allowed", "Washer", "Patio or balcony", "TV", "Air conditioning", "Stove", "Gym", "Iron", "Hangers", "Refrigerator"]',
       '["Washer", "Air conditioning", "Breakfast", "Kitchen", "Dryer", "Wifi", "TV with standard cable", "Free parking on premises", "Long term stays allowed", "Elevator"]',
       '["Pool", "Washer", "First aid kit", "Heating", "Shampoo", "Gym", "Kitchen", "Essentials", "Wifi", "Fire extinguisher", "TV with standard cable", "Free parking on premises", "Smoke alarm", "Long term stays allowed", "Hot tub", "Elevator"]',
       ...,
       '["Washer", "Air conditioning", "Smoking allowed", "First aid kit", "Carbon monoxide alarm", "Dedicated workspace", "Kitchen", "Wifi", "Fire extinguisher", "Pets allowed", "Free parking on premises", "Smoke alarm", "Security cameras on property", "Long term stays allowed", "TV"]',
       '["Paid parking on premises", "Shampoo", "Kitchen", "Cooking basics", "Long term stays allowed", "Dining table", "Elevator", "Hot water", "Pool", "Private entrance", "Dishes and silverware", "Essentials", "Wifi", "Microwave", "Carbon monoxide alarm", "Smoke alarm", "Hair dryer", "Shower gel", "Washer", "Patio or balcony", "Backyard", "Hot water kettle", "TV", "Bed linens", "Air conditioning", "Stove", "Clothing storage", "Room-darkening shades", "Hangers", "Refrigerator"]',
       '["Kitchen", "Lockbox", "Drying rack for clothing", "Pool table", "Dining table", "Long term stays allowed", "Elevator", "Hot water", "Pool", "Private entrance", "Self check-in", "Dishes and silverware", "Essentials", "Wifi", "Microwave", "Carbon monoxide alarm", "Smoke alarm", "Hair dryer", "Washer", "Patio or balcony", "Backyard", "Hot water kettle", "TV", "Bed linens", "Air conditioning", "Stove", "Gym", "Clothing storage", "Room-darkening shades", "Hangers", "Refrigerator"]'],
      dtype=object)

In [10]:
listings2.accommodates.unique()

array([ 3,  2,  4,  5,  1, 16, 12, 13,  6,  8,  7, 11, 10, 14,  9, 15,  0],
      dtype=int64)

# calendar

In [11]:
calendar = pd.read_csv('calendar2.csv')
calendar.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,27934,2022-12-28,f,"$1,905.00","$1,905.00",3,90
1,27934,2022-12-29,f,"$1,905.00","$1,905.00",3,90
2,27934,2022-12-30,f,"$1,905.00","$1,905.00",3,90
3,27934,2022-12-31,f,"$1,905.00","$1,905.00",3,90
4,27934,2023-01-01,f,"$1,905.00","$1,905.00",3,90

In [12]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5786345 entries, 0 to 5786344
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            object
 2   available       object
 3   price           object
 4   adjusted_price  object
 5   minimum_nights  int64
 6   maximum_nights  int64
dtypes: int64(3), object(4)
memory usage: 309.0+ MB

In [13]:
calendar.date = pd.to_datetime(calendar.date)
display(calendar.date.min(), calendar.date.max())

Timestamp('2022-12-28 00:00:00')

Timestamp('2024-01-02 00:00:00')

# reviews

In [14]:
reviews = pd.read_csv('reviews.csv')
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,27934,1094339,2012-04-07,1368195,Michael,We stayed in the apartment for a week and we e...
1,27934,1241042,2012-05-07,2007324,Scott,My girlfriend and I recently stayed in Nuttee'...
2,27934,1523384,2012-06-20,2263352,Marc,I stayed for one month at the condo and was re...
3,27934,1655571,2012-07-08,558987,Leyla,Nuttee was a great host! I really enjoyed her ...
4,27934,1972192,2012-08-13,2359865,Rachel,Nuttee was an amazing host. She and her daught...